### PR TITLE
update newest esx

### PR DESCRIPTION
**Pull request by Tinky124**
No more essentialmode!

### CODE REVIEW

**Comment by brandinio** [comment]
@Tinky124 Not sure why, but I'm getting this error when I run your latest commit.

```
Creating script environments for trew_hud_ui
Error loading script server/server.lua in resource trew_hud_ui: Invalid Lua type in __data
stack traceback:
	[C]: in upvalue '_in'
	citizen:/scripting/lua/natives_server.lua:1057: in function 'RegisterCommand'
	@trew_hud_ui/server/server.lua:1: in main chunk
Failed to load script server/server.lua.
```

Do you know what might be causing this?

**Comment by Khristos94** [comment]
@vortisrd 

Not sure why, but I'm getting this error when I run your latest commit.

Creating script environments for trew_hud_ui
Error loading script server/server.lua in resource trew_hud_ui: Invalid Lua type in __data
stack traceback:
	[C]: in upvalue '_in'
	citizen:/scripting/lua/natives_server.lua:1057: in function 'RegisterCommand'
	@trew_hud_ui/server/server.lua:1: in main chunk
Failed to load script server/server.lua.

**Comment by Khristos94** [comment]
@vortisrd

[](https://photos.app.goo.gl/9hGrtCH3NHM3ZEHJ9)

**Comment by Khristos94** [comment]
@vortisrd
Not sure why, but I'm getting this error when I run your latest commit.

Capture
](url)

Do you know what might be causing this?
Thank you

**Comment by Tinky124** [comment]
@Khristos94 @Jigara https://github.com/vortisrd/trew_hud_ui/pull/38

**Pull request merged**
