### PR TITLE
Optimization, fixed server hitch warnings!

### PR DESCRIPTION
**Pull request by Tinky124**

### CODE REVIEW

**Review by Tinky124 — COMMENTED** [review]
Little update

**Comment by reen389** [comment]
Hello, thanks for you work but actually the script dont work anymore with you changes. Now there is no way to get the money and job informationen from the server. 
Did I missed something or do you dont use them? Cause the server function makes hitch times and needs a lot of resources but with you update it doesnt work :(

**Comment by vortisrd** [comment]
> Little update

:)

**Comment by Borea** [comment]
Works fine. Thanks

**Pull request merged**
