### PR TITLE
Update client.lua

### PR DESCRIPTION
**Pull request by Demo4889**
Update for new es_extended not displaying UI during initial startup.

### CODE REVIEW

**Comment by m0iises19** [comment]
error
hud bug

**Comment by Demo4889-TLRP** [comment]
What line is that @m0iises?

**Comment by m0iises19** [comment]
locationMessage = string.format(
				Locales[Config.Locale]['you_are_on_location'],
				locationMessage
			)

115 --> Locales[Config.Locale]['you_are_on_location'],

**Comment by Demo4889-TLRP** [comment]
Definitely check your locale file to make sure everything is right. Sometimes spelling of locale and local can throw it off

**Comment by m0iises19** [comment]
the local file is by default, everything is by default except what you changed...

**Comment by Demo4889** [comment]
I never changed anything around that line location. I will look into in about an hour once I get home from work.

**Comment by gabrielcalderon** [comment]
Without the changes on this PR, i can't get the HUD to show up. Adding these changes made the HUD show up 👍

**Comment by gabrielcalderon** [comment]
@vortisrd

**Comment by iliasroleplay** [comment]
true hero

**Comment by vortisrd** [comment]
Like I said in the README, I'm not active in the development of the HUD anymore, since I don't play the game and I don't intend to go back.

Regardless, It's nice to see my project growing up beyong it's limits. Thanks for the commit. I've merged it to the master repo.

**Pull request merged**
